---
spring:
  profiles: eureka-primary
  cloud:
    config:
      uri: http://spotlight-config-server.herokuapp.com/

eureka:
  instance:
    preferIpAddress: true
  enableSelfPreservation: false
  client:
    name: eureka
    shouldOnDemandUpdateStatusChange: false
    serviceUrl:
      defaultZone: http://spotlight-eureka-secondary.herokuapp.com/eureka/

---
spring:
  profiles: eureka-secondary
  cloud:
    config:
      uri: http://spotlight-config-server.herokuapp.com/

eureka:
  instance:
    preferIpAddress: true
  enableSelfPreservation: false
  client:
    name: eureka
    shouldOnDemandUpdateStatusChange: false
    serviceUrl:
      defaultZone: http://spotlight-eureka-primary.herokuapp.com/eureka/

