---
spring:
 application:
   name: gateway
 cloud:
   config:
     uri: https://spotlight-config-server.herokuapp.com/

gateway:
  ribbon:
    DeploymentContextBasedVipAddresses: spotlight-gateway
    ReadTimeout: 30000
    ConnectTimeout: 30000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      requestCache:
        enabled: false
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true

zuul:
 ignoredServices: '*'
 routes:
  beehive-services:
    path: /**

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: https://spotlight-eureka-primary.herokuapp.com/eureka/,https://spotlight-eureka-secondary.herokuapp.com/eureka/

