---
spotlight-services:
  ribbon:
    DeploymentContextBasedVipAddresses: spotlight-services
    ReadTimeout: 30000
    ConnectTimeout: 30000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: false

hystrix:
  command:
    default:
      requestCache:
        enabled: false
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true

zuul:
 ignoredServices: '*'
 routes:
  spotlight-services:
    path: /**

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone:  http://spotlight-eureka-primary.herokuapp.com/eureka/, http://spotlight-eureka-secondary.herokuapp.com/eureka/


spring:
 application:
   name: spotlight-gateway
 cloud:
   config:
     uri: http://spotlight-config-server.herokuapp.com/