hystrix:
  command:
    default:
      requestCache:
        enabled: false
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true
server:
  port: 8090

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: https://spotlight-eureka-primary.herokuapp.com/eureka/, https://spotlight-eureka-secondary.herokuapp.com/eureka/

spring:
  application:
    name: spotlight-services
  cloud:
    config:
      uri: https://spotlight-config-server.herokuapp.com/


spotlight:
      url: http://www.dbpedia-spotlight.com


json-ld:
      context: "http://www.jsonld-context.io/api/v1?ontology=http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core,http://www.w3.org/2005/11/its/rdf,http://www.w3.org/2001/XMLSchema"