hystrix:
  command:
    default:
      requestCache:
        enabled: false
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://spotlight-eureka-primary.herokuapp.com/eureka/, http://spotlight-eureka-secondary.herokuapp.com/eureka/

spring:
  application:
    name: spotlight-services
  cloud:
    config:
      uri: http://spotlight-config-server.herokuapp.com/


spotlight:
      url: http://model.dbpedia-spotlight.org


json-ld:
      context: "http://www.jsonld-context.io/api/v1?ontology=http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core,http://www.w3.org/2005/11/its/rdf"