eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://spotlight-eureka-primary.herokuapp.com/eureka/, http://spotlight-eureka-secondary.herokuapp.com/eureka/

---
server:
  port: 8200
spring:
  profiles: de
  application:
    name: spotlight-model-de
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8201
spring:
  profiles: en
  application:
    name: spotlight-model-en
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8202
spring:
  profiles: es
  application:
    name: spotlight-model-es
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8203
spring:
  profiles: fr
  application:
    name: spotlight-model-fr
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8204
spring:
  profiles: it
  application:
    name: spotlight-model-it
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8205
spring:
  profiles: nl
  application:
    name: spotlight-model-nl
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8206
spring:
  profiles: hu
  application:
    name: spotlight-model-hu
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8207
spring:
  profiles: pt
  application:
    name: spotlight-model-pt
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8208
spring:
  profiles: ru
  application:
    name: spotlight-model-ru
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8209
spring:
  profiles: sv
  application:
    name: spotlight-model-sv
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8209
spring:
  profiles: tr
  application:
    name: spotlight-model-tr
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672
---
server:
  port: 8210
spring:
  profiles: da
  application:
    name: spotlight-model-da
  cloud:
    config:
      uri: http://localhost:8001
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost
    port: 5672