hystrix:
  command:
    default:
      requestCache:
        enabled: false
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            interruptOnTimeout: true
server:
  port: 8090

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/, http://localhost:8011/eureka/

spring:
  application:
    name: spotlight-services
  cloud:
    config:
      uri: http://localhost:8001


spotlight:
      url: http://model.dbpedia-spotlight.org


json-ld:
      context: "http://www.jsonld-context.io/api/v1?ontology=http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core,http://www.w3.org/2005/11/its/rdf"