eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/, http://localhost:8011/eureka/


spring:
  cloud:
    config:
      uri: http://localhost:8001