server:
  port: 8092

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/, http://localhost:8010/eureka/

spring:
  application:
    name: spotlight-statistical
  cloud:
    config:
      uri: http://localhost:8001
