server:
  port: 8091

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/, http://localhost:8010/eureka/

spring:
  application:
    name: spotlight-lucene
  cloud:
    config:
      uri: http://localhost:8501
